name: RuffLint
# Runs the workflow on the below events:
# 1. on pull request raised to trunk branch.
# 2. on push event to trunk branch.
on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  lint-markdown:
    runs-on: ubuntu-latest
    name: Lint MicroPython
    steps:
      - name: checkout repo content
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install and run Ruff linter
        uses: astral-sh/ruff-action@278981a28ce3188b1e39527901f38254bf3aac89 # v4.1.0
        with:
          version: 0.15.22
          src: >-
            src/main.py
            src/lib/aes.py
            src/lib/atclient.py
            src/lib/iv_nonce.py
            src/lib/logging.py
            src/lib/ntp_client.py
            src/lib/pem_service.py
            src/lib/uasn1.py
