name: RunTests
# Runs the workflow on the below events:
# 1. on pull request raised to trunk branch.
# 2. on push event to trunk branch.
on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  lint-markdown:
    runs-on: ubuntu-20.04
    name: Run Tests
    steps:
      - name: checkout repo content
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: Install MicroPython and run tests
        run: |
          DLURL="https://github.com/atsign-foundation/micropython/releases/download/"
          ATMPRELDIR="1.22.0_g099e9a1a0_AES_CTR/"
          ATMPRELBIN="micropython_1.22.0_g099e9a1a0_linux_x64.tgz"
          wget ${DLURL}${ATMPRELDIR}${ATMPRELBIN}
          tar -xvf ${ATMPRELBIN}
          export MICROPY_MICROPYTHON="$(pwd)/micropython"
          cd tests
          ./run-tests.py -d atsign
          tar -cvzf results.tgz results
      - name: Upload results
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        with:
          name: atsign tests
          path: tests/results.tgz
          retention-days: 7

